name = "aprendemais"
main = "src/worker.js"
compatibility_date = "2026-09-29"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "aprende_leads"
database_id = "0d63ff29-1408-4772-a78d-62d8dac0d52b"
migrations_dir = "migrations"
